### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount": 100
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount": 100
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "1fbcdd0d3b1b47ccb72577a0a63235d1",
  "accountNumber": "1000000002",
  "amount": 100
}


### query transaction
GET http://localhost:8080/transaction/5997434a1f7647c08d2693d06c27ab74